package com.board.bdi.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BoardInfoVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시판번호. */
	private Integer binum;

	/** 게시판제목. */
	private String bitable;

	/** 게시판내용. */
	private String bitext;

	/** 게시판파일. */
	private String bifile;

	/** 게시판등록일. */
	private String bicredate;

	/** 게시판수정일. */
	private String bimodat;

	/** 게시판조회수. */
	private Integer bicnt;

	/** 게시판활성여부. */
	private Byte biactive;

	/** 새 테이블. */
	private UserInfoVo userInfo;

	/** 새 테이블 목록. */
	private Set<CommentInfoVo> commentInfoSet;

	/**
	 * 생성자.
	 */
	public BoardInfoVo() {
		this.commentInfoSet = new HashSet<CommentInfoVo>();
	}

	/**
	 * 게시판번호을 설정합니다..
	 * 
	 * @param binum
	 *            게시판번호
	 */
	public void setBinum(Integer binum) {
		this.binum = binum;
	}

	/**
	 * 게시판번호을 가져옵니다..
	 * 
	 * @return 게시판번호
	 */
	public Integer getBinum() {
		return this.binum;
	}

	/**
	 * 게시판제목을 설정합니다..
	 * 
	 * @param bitable
	 *            게시판제목
	 */
	public void setBitable(String bitable) {
		this.bitable = bitable;
	}

	/**
	 * 게시판제목을 가져옵니다..
	 * 
	 * @return 게시판제목
	 */
	public String getBitable() {
		return this.bitable;
	}

	/**
	 * 게시판내용을 설정합니다..
	 * 
	 * @param bitext
	 *            게시판내용
	 */
	public void setBitext(String bitext) {
		this.bitext = bitext;
	}

	/**
	 * 게시판내용을 가져옵니다..
	 * 
	 * @return 게시판내용
	 */
	public String getBitext() {
		return this.bitext;
	}

	/**
	 * 게시판파일을 설정합니다..
	 * 
	 * @param bifile
	 *            게시판파일
	 */
	public void setBifile(String bifile) {
		this.bifile = bifile;
	}

	/**
	 * 게시판파일을 가져옵니다..
	 * 
	 * @return 게시판파일
	 */
	public String getBifile() {
		return this.bifile;
	}

	/**
	 * 게시판등록일을 설정합니다..
	 * 
	 * @param bicredate
	 *            게시판등록일
	 */
	public void setBicredate(String bicredate) {
		this.bicredate = bicredate;
	}

	/**
	 * 게시판등록일을 가져옵니다..
	 * 
	 * @return 게시판등록일
	 */
	public String getBicredate() {
		return this.bicredate;
	}

	/**
	 * 게시판수정일을 설정합니다..
	 * 
	 * @param bimodat
	 *            게시판수정일
	 */
	public void setBimodat(String bimodat) {
		this.bimodat = bimodat;
	}

	/**
	 * 게시판수정일을 가져옵니다..
	 * 
	 * @return 게시판수정일
	 */
	public String getBimodat() {
		return this.bimodat;
	}

	/**
	 * 게시판조회수을 설정합니다..
	 * 
	 * @param bicnt
	 *            게시판조회수
	 */
	public void setBicnt(Integer bicnt) {
		this.bicnt = bicnt;
	}

	/**
	 * 게시판조회수을 가져옵니다..
	 * 
	 * @return 게시판조회수
	 */
	public Integer getBicnt() {
		return this.bicnt;
	}

	/**
	 * 게시판활성여부을 설정합니다..
	 * 
	 * @param biactive
	 *            게시판활성여부
	 */
	public void setBiactive(Byte biactive) {
		this.biactive = biactive;
	}

	/**
	 * 게시판활성여부을 가져옵니다..
	 * 
	 * @return 게시판활성여부
	 */
	public Byte getBiactive() {
		return this.biactive;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param userInfo
	 *            새 테이블
	 */
	public void setUserInfo(UserInfoVo userInfo) {
		this.userInfo = userInfo;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public UserInfoVo getUserInfo() {
		return this.userInfo;
	}

	/**
	 * 새 테이블 목록을 설정합니다..
	 * 
	 * @param commentInfoSet
	 *            새 테이블 목록
	 */
	public void setCommentInfoSet(Set<CommentInfoVo> commentInfoSet) {
		this.commentInfoSet = commentInfoSet;
	}

	/**
	 * 새 테이블를 추가합니다..
	 * 
	 * @param commentInfo
	 *            새 테이블
	 */
	public void addCommentInfo(CommentInfoVo commentInfo) {
		this.commentInfoSet.add(commentInfo);
	}

	/**
	 * 새 테이블 목록을 가져옵니다..
	 * 
	 * @return 새 테이블 목록
	 */
	public Set<CommentInfoVo> getCommentInfoSet() {
		return this.commentInfoSet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((binum == null) ? 0 : binum.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		BoardInfoVo other = (BoardInfoVo) obj;
		if (binum == null) {
			if (other.binum != null) {
				return false;
			}
		} else if (!binum.equals(other.binum)) {
			return false;
		}
		return true;
	}

}
